### PR TITLE
Add very rough guide

### PR DESCRIPTION
**Pull request by jasonm23**
@adereth I harvested your build images from Twitter to make a quick and dirty rough guide. I'll add a link in the ./README.md

### CODE REVIEW

**Comment by jasonm23** [comment]
https://github.com/emacsfodder/dactyl-keyboard/blob/add-rough-guide-to-pcb-build/guide/README.md for pre-viewing

**Comment by adereth** [comment]
Thanks!

**Comment by jasonm23** [comment]
Obviously needs a ton of work, but I assume you don't have an army of clones to do your bidding. (please supply info if you do!)

**Comment by jasonm23** [comment]
You can leave breadcrumbs in #8 (eg. what's the deal with the parallel resistors on the teensy.) and I will be happy to write them up into the guide.  Same with any more photos etc.

Keen to assist, what I consider to be a project of some gravitas.

**Pull request merged**
